### ISSUE TITLE
how to use specific urdf

### ISSUE THREAD

**Issue by xiepeter** [mrsp/serow#18]
I would like to ask if I want to use my specific urdf, what I need to do is only to exchange the urdf file?

**Comment by MichaelMarav** [comment]
In order to use your urdf, you will need to create a .json file for your robot where you specify the name of the urdf file and other relevant parameters. For reference check the config/ *.json. Then, once you initialize serow you need to pass the name of the config file (check the following file:  test/go1_test.cpp)
