### ISSUE TITLE
our urdf not working

### ISSUE THREAD

**Issue by yl7094** [mrsp/serow#3]
Dear Serow's developer,

Thank you for your wonderful library. We test the Serow library in our Linux Ubuntu 16.04 LTS PC and only the NAO bag could work, the Valkyrie bag is running without any error but not showing anything by serow_utils in rviz.

We do follow what you did in structure and follow what you write for NAO urdf and config/estimation_params.yaml but the result is similar to the Valkyrie bag. There is no error but also not showing any result by serow_utils display in in rviz. 

Do you know what should we do to avoid this issue?  Thank you!

**Comment by mrsp** [comment]
Hello and many thanks for the feedback!

I fixed the issue. The urdf of valkyrie had a continuous joint for the Lidar sensor which SEROW treated as an actuated joint. 

Kindly pull the master branch and you will be able to run the valkyrie bag file after changing in the config/estimation_params_valkyrie.yaml the path to the share/valkyrie_sim.urdf

Let me know if it worked for you.

**Comment by yl7094** [comment]
Thank you for your quick response! We appreciate it!

What file should we revise if we want to apply serow on other robot models? Currently, we only revised URDF based on NAO's model and Specify topics on config/estimation_params.yaml. But it doesn't work, at least it didn't show anything in  serow_utils after running the NAO bag file.

We saw the master branch change the share/urdf/valkyrie_sim.urdf from share/urdf/valkyrie_sim_gazebo_sync.urdf. However, we do not have that issue of path by directly downloading by git. There is a little more detail in our testing. 

We run the NAO and capture its serow/pose is changing all the time. Therefore, we tried to capture some data by running your valkyrie and our URDF but there is serow/pose but no data showing neither on capture or serow_utils.

Another thing may cause the issue of our robot is we do not have a bag file of our robot so we run your NAO bagfile because it is running successfully. We follow what you did in the NAO file and adding some sensors that not listed in our robot but the result just nothing. I guess if you can help us how to create the bagfile may be helpful as well.

Thank you for your help!

**Comment by mrsp** [comment]
Hello  on which robot are you trying to run serow? 

In order to run serow with your robot in real-time you need the following:
a) A URDF of your robot
b) An imu in body (base_link), joint encoders in every actuated joint, pressure (i.e. FSRs) OR Force/Torque sensors in the feet. Optionally you can use an external LIDAR or Camera to fix kinematic drift as demonstrated in our results.

In other words you need the following topics:
An Imu topic publishing imu sensor_msgs, joint_states topic publishing joint_state sensor_msg, and F/T topic publishing wrench_msgs. Optionally a Lidar Odometry or Visual Odometry topic to incorporate external odometry measurements.

Then you configure the config/estimation_params.yaml accordingly and launch 
roslaunch serow serow.launch

I'll be happy to provide feedback on how to "tune" serow (e.g. fill in the estimation_params.yaml).
 
P.S. to launch our valkyrie experiment as shown in our video just run: 
rosbag play valk.bag
roslaunch serow serow_valkyrie.launch
roslaunch serow_utils serow_utils.launch
